apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-db-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Release.Namespace }}-secrets
    kind: SecretStore
  target:
    name: grafana-db-secret
    creationPolicy: Owner
  data:
  - secretKey: GF_DATABASE_PASSWORD
    remoteRef:
      key: {{ .Values.aws_secret_name }}
      property: password