apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: twistlock-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Release.Namespace }}-secrets
    kind: SecretStore
  target:
    name: twistlock-secrets
    creationPolicy: Owner
  data:
  - secretKey: service-parameter
    remoteRef:
      key: {{ .Values.aws_secret_name }}
      property: service_parameter
  - secretKey: defender-ca.pem
    remoteRef:
      key: {{ .Values.aws_secret_name }}
      property: defender.ca
  - secretKey: defender-client-cert.pem
    remoteRef:
      key: {{ .Values.aws_secret_name }}
      property: defender.client_cert
  - secretKey: defender-client-key.pem
    remoteRef:
      key: {{ .Values.aws_secret_name }}
      property: defender.client_key
  - secretKey: admission-cert.pem
    remoteRef:
      key: {{ .Values.aws_secret_name }}
      property: admission.cert
  - secretKey: admission-key.pem
    remoteRef:
      key: {{ .Values.aws_secret_name }}
      property: admission.key