apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Release.Namespace }}-secrets
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-secret
    creationPolicy: Owner
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: {{ .Values.db_secret.name }}
      property: {{ .Values.db_secret.key }}