apiVersion: v1
kind: Service
metadata:
  name: imageswap
  labels:
    app: imageswap
    resource: service
spec:
  ports:
  - name: https
    port: 443
    targetPort: 5000
  selector:
    app: imageswap
  sessionAffinity: None
  type: ClusterIP