apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: rewrite-basepath
  annotations:
    kubernetes.io/ingress.class: kong
config: 
  replace:
    uri: '/$(uri_captures[1])'
plugin: request-transformer