apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kiali
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Release.Namespace }}-secrets
    kind: SecretStore
  target:
    name: kiali
    creationPolicy: Owner
  data:
  - secretKey: oidc-secret
    remoteRef:
      key: dt-shared-{{ .Values.env }}-{{ .Release.Namespace }}-kiali
      property: oidc-secret