
{{- range $v := .Values.externalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $.Release.Name }}-{{ $v.name }}
spec:
  refreshInterval: {{ $v.refreshInterval | default "1m" | quote}}
  secretStoreRef:
    name: {{ $v.secretStore.name }}
    kind: {{ $v.secretStore.kind | default "SecretStore" }}
  target:
    name: {{ $.Release.Name }}-{{ $v.name }}
    creationPolicy: Owner
  data:
  {{- range $v2 := $v.secrets }}
  - secretKey: {{ $v2.varname }}
    remoteRef:
      key: {{ $v2.name }}
      property: {{ $v2.property }}
      decodingStrategy: {{ $v2.decodingStrategy | default "None" }}
  {{- end }}
{{- end }}