apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dynakube
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Release.Namespace }}-secrets
    kind: SecretStore
  target:
    name: dynakube
    creationPolicy: Owner
  data:
  - secretKey: apiToken
    remoteRef:
      key: {{ .Values.aws_secret_name }}
      property: apiToken
  - secretKey: dataIngestToken
    remoteRef:
      key: {{ .Values.aws_secret_name }}
      property: dataIngestToken